### ISSUE TITLE
Nothing generated

### ISSUE THREAD

**Issue by DaTeL237** [noties/SharedPreferencesGenerator#1]
Hello,

~~After I add SharedPreferencesGenerator to my project I try to reproduce the Simplest example. The annotations are correctly recognized and my project compiles.~~

~~However no code is generated. Should I expect the to-be-generated classes to be generated automatically?~~

It turns out I was using another apt plugin. Still with the correct one the build script fails on the apt step, see log (file attachment is failing):

> FAILURE: Build failed with an exception.
> 
> What went wrong:
> A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:apt'.
>    Could not find SharedPreferencesGenerator:annotations:unspecified.
>      Searched in the following locations:
>          https://jcenter.bintray.com/SharedPreferencesGenerator/annotations/unspecified/annotations-unspecified.pom
>          https://jcenter.bintray.com/SharedPreferencesGenerator/annotations/unspecified/annotations-unspecified.jar
>          https://repo1.maven.org/maven2/SharedPreferencesGenerator/annotations/unspecified/annotations-unspecified.pom
>          https://repo1.maven.org/maven2/SharedPreferencesGenerator/annotations/unspecified/annotations-unspecified.jar
>          https://oss.sonatype.org/content/repositories/snapshots/SharedPreferencesGenerator/annotations/unspecified/annotations-unspecified.pom
>          https://oss.sonatype.org/content/repositories/snapshots/SharedPreferencesGenerator/annotations/unspecified/annotations-unspecified.jar

**Comment by noties** [comment]
Hi! Yes, I've just checked & found out that local dependencies (that are attached through `compile project(...)`) has no dependency information. Current solution would change the `apt` dependency line to:

``` groovy
    apt ('ru.noties.spg:processor:1.0.0') {
        exclude module: 'annotations'
    }
```

**Comment by DaTeL237** [comment]
Ahh indeed, that fixes the problem. In the meanwhile I wrote my own wrapper, but thanks for the fast response & solution.

Edit: If you put the exclude on the main page too I'm sure it will help others as well
