### ISSUE TITLE
Current processor not updated?

### ISSUE THREAD

**Issue by warot** [noties/SharedPreferencesGenerator#2]
I think the current processor in Maven Central hadn't been updated to the latest commit yet. The problem is I cannot custom deserializer and serializer.

Please fix this issue.

Thanks,
Warot

**Comment by noties** [comment]
Hi! I've just checked and found out, that if you are using `jcenter()` the artifact is out dated. Anyway `mavenCentral()` has the right one.

**Comment by warot** [comment]
It shouldn't has difference sources with same version even if on different repository.
Please update it because I need to use jcenter() for other libraries.

Thanks.

**Comment by noties** [comment]
Yes, I agree. I will release `1.0.1` to update jcenter's cache
