### ISSUE TITLE
SPG withou annotations

### ISSUE THREAD

**Issue by gingo** [noties/SharedPreferencesGenerator#4]
Hello, many thanks for this great library!

Is possible to use it without annotations? Or there is another reason to have three separated maven/gradle packages?

**Comment by noties** [comment]
Hey! Glad it helped!
Well, the idea was to share the code between 2 separate modules. At that time I saw it as the only option. But right now I think we can do something about it. For example, keep the modules structure. Create a fatJar(fatAar) for `core` module with annotations. Use provided as a dependency scope in annotation processor for annotations. I think it will do. I will try to make the changes soon.
