### ISSUE TITLE
Gradle DSL method not found: 'apt()' 

### ISSUE THREAD

**Issue by gingo** [noties/SharedPreferencesGenerator#5]
Will be great to mention how to make apt section in dependencies work :)

For example this SO thread worked for me: 

http://stackoverflow.com/questions/37754805/how-to-setup-butterknife-plugin-in-android-studio/37754907#37754907

**Comment by noties** [comment]
Sure, sorry about that, I thought that every developer is accustomed with the great `apt` tool :)
