### ISSUE TITLE
Empty string replaced with null

### ISSUE THREAD

**Issue by janbina** [noties/SharedPreferencesGenerator#6]
I want my String preference default value to be empty string (""), but the library ignores it and returns null instead. If I use any other value, it works as expected.

**Comment by noties** [comment]
Yes, it's true. There are two workarounds that I see right now:
* if you supply a default value for a key (via `@SPGKey` annotation) put `defaultValue = "${\"\"}"` as an evaluation string
* marking `defString` on the `@SPGPreference` works as expected.

**Comment by janbina** [comment]
Ok, thank you for fast reply.
